# Generated by Django 3.2.15 on 2022-08-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_hospital_app', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
